name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libffi-dev libssl-dev libxml2-dev libxslt1-dev libjpeg8-dev zlib1g-dev git wget unzip
        pip install --upgrade pip
        pip install Cython==0.29.30
        pip install pygame
        pip install kivy==2.1.0
        pip install buildozer==1.5.0
        
    - name: Prepare buildozer.spec
      run: |
        cd ${{ github.workspace }}
        # Ensure SDK license acceptance is set in buildozer.spec
        grep -q "android.accept_sdk_license" buildozer.spec && sed -i 's/android.accept_sdk_license = .*/android.accept_sdk_license = True/g' buildozer.spec || echo "android.accept_sdk_license = True" >> buildozer.spec
        # Add SDK and NDK paths to buildozer.spec
        echo "" >> buildozer.spec
        echo "[buildozer]" >> buildozer.spec
        echo "log_level = 2" >> buildozer.spec
        
    - name: Build APK
      run: |
        cd ${{ github.workspace }}
        # Let buildozer install SDK automatically
        buildozer android debug --verbose
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: gta-ifp-editor-apk
        path: bin/*.apk
